---
- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: True
  serial: 1
  
  vars_prompt:
  - name: "vc"
    prompt: "vCenter Sever FQDN"
    private: no
  - name: "user"
    prompt: "vCenter username"
    private: no
  - name: "pw"
    prompt: "MOAR passwords"
    private: yes
  - name: "vm"
    prompt: "Enter a VM name"
    private: no

  tasks:
   - vsphere_guest:
       vcenter_hostname: "{{vc}}"
       username: "{{user}}"
       password: "{{pw}}"
       guest: "{{vm}}"
       validate_certs: no
       state: powered_on
       vm_disk:
         disk1:
           size_gb: 20
           type: thin
           datastore: Datastore
       vm_nic:
         nic1:
           type: vmxnet3
           network: vm
           network_type: standard
       vm_hardware:
         memory_mb: 512
         num_cpus: 1
         osid: centos64Guest
         scsi: paravirtual
       esxi:
         datacenter: Xstreamdatastorage
         hostname: 10.60.45.38
