---

- hosts: local
  user: root
  connection: ssh
  gather_facts: yes
  become: yes
  tasks:
   - name: ping all hosts
     ping:
   - name: remove few problem
     yum: pkg=python2-crypto-2.6.1-15.el7.x86_64 state=absent 
   - name: change  hostname
     hostname: name=aio1.xsportal.local
   - name: set hostname permanently
     shell: hostnamectl set-hostname aio1.xsportal.local
   - name: add hostname to /etc/hosts file to resolve it locally
     lineinfile:
       path: /etc/hosts
       line: '192.168.219.128 aio1.xsportal.local aio1'
       backup: yes
     register: result
   - debug:
       var: result
     #failed_when: "command_result.rc != 0"
   - name: change dir
     chdir: /abhishek
     command: cp $HOME/xsdeploy-test.conf /root/abhishek
     register: result
   - debug:
       var: result

