--- # RUNONCE PLAYBOOK EXAMPLE
- hosts: local
  user: root
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Run the uptime command on all hosts and log it
     raw: /usr/bin/uptime >> uptime.log
   - name: List the /var directory and log it
     raw: ls -al /var >> dir.list
     run_once: true
