---
- hosts: 127.0.0.1
  connection: local
  become: no

  tasks:
   - name: Gather facts from standalone ESXi server having datacenter as
     vmware_guest:
      hostname: 10.60.45.38
      username: administrator@nestlab.local
      password: Pa$$w0rd97
      datacenter: xStreamIndia
      validate_certs: no
      name: A001US014XVM003
      uuid: 4200277e-ad59-94ad-a7b4-9f62745af2d0
      name: A111232323



