---
- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: True
  serial: 1

  tasks:
    - name: Create a VM from a template
      vmware_guest:
        hostname: 10.60.45.38
        username: administrator@nestlab.local
        password: Pa$$w0rd97
        validate_certs: no
        datacenter: xStreamIndia
        folder: xStreamIndia/vm
        name: testvm_234
        state: poweredon
        template:
        disk:
        - size_gb: 20
          type: thin
          datastore: datastore 1
        hardware:
          memory_mb: 512
          num_cpus: 2
          num_cpu_cores_per_socket: 1
          scsi: paravirtual
          memory_reservation: 512
          memory_reservation_lock: True
          mem_limit: 512
          mem_reservation: 512
          cpu_limit: 1024
          cpu_reservation: 1024
          max_connections: 5
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: False
        cdrom:
          type: iso
          iso_path: "[datastore 1] CentOS-7-x86_64-Minimal-1708_SHARAN.iso"
        networks:
        - name: VM Network
#         mac: aa:bb:dd:aa:00:14
          device_type: e1000
          vlan: DSwitch_xStream_India
        wait_for_ip_address: no
      delegate_to: localhost
      register: deploy    
