---
- hosts: 127.0.0.1
  connection: local
  become: no

  tasks:
   - name: Gather facts from standalone ESXi server having datacenter as
     vmware_guest_facts:
      hostname: 10.60.45.38
      username: administrator@nestlab.local
      password: Pa$$w0rd97
      datacenter: xStreamIndia
      validate_certs: no
      name: A001US014XVM003
     






