---
- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: True
  
  tasks:
   - vmware_guest_find:
       hostname: 10.60.45.38
       username: administrator@nestlab.local
       password: Pa$$w0rd97
       validate_certs: no
       name: A001US014XVM009
     register: vm_folder  
